export const ITEM_CLASS_CATALOG = Object.freeze([
  {
    code: 'PURCHASED_MATERIAL',
    name: 'Purchased Material',
    capabilities: { inventory: true, purchasable: true, consumable: true },
  },
  {
    code: 'PACKAGING',
    name: 'Packaging Material',
    capabilities: { inventory: true, purchasable: true, consumable: true },
  },
  {
    code: 'COMPONENT',
    name: 'Purchased Component',
    capabilities: { inventory: true, purchasable: true, consumable: true },
  },
  {
    code: 'INTERMEDIATE',
    name: 'Manufactured Intermediate',
    capabilities: { inventory: true, manufacturable: true, consumable: true, sellable: true },
  },
  {
    code: 'FINISHED_GOOD',
    name: 'Finished Good',
    capabilities: { inventory: true, manufacturable: true, sellable: true },
  },
  {
    code: 'BY_PRODUCT',
    name: 'Recoverable By-product',
    capabilities: {
      inventory: true,
      purchasable: true,
      manufacturable: true,
      consumable: true,
      sellable: true,
    },
  },
  {
    code: 'CONSUMABLE',
    name: 'Consumable',
    capabilities: { inventory: true, purchasable: true, consumable: true },
  },
  {
    code: 'SPARE',
    name: 'Spare Part',
    capabilities: { inventory: true, purchasable: true, consumable: true },
  },
  {
    code: 'SERVICE',
    name: 'Service',
    capabilities: { inventory: false, purchasable: true, sellable: true },
  },
]);

export const ITEM_ATTRIBUTE_CATALOG = Object.freeze([
  {
    code: 'classification_temperature',
    label: 'Classification Temperature',
    dataType: 'select',
    unit: '°c',
    allowedValues: [
      { value: '1260', label: '1260 °C' },
      { value: '1425', label: '1425 °C' },
    ],
  },
  {
    code: 'density',
    label: 'Density',
    dataType: 'number',
    unit: 'kg/m³',
    validation: { min: 1, precision: 3 },
  },
  {
    code: 'length',
    label: 'Length',
    dataType: 'number',
    unit: 'mm',
    validation: { min: 0.001, precision: 3 },
  },
  {
    code: 'width',
    label: 'Width',
    dataType: 'number',
    unit: 'mm',
    validation: { min: 0.001, precision: 3 },
  },
  {
    code: 'thickness',
    label: 'Thickness',
    dataType: 'number',
    unit: 'mm',
    validation: { min: 0.001, precision: 3 },
  },
  { code: 'grade', label: 'Product Grade', dataType: 'text', validation: { maxLength: 80 } },
  {
    code: 'chemical_grade',
    label: 'Chemical / Technical Grade',
    dataType: 'text',
    validation: { maxLength: 120 },
  },
  {
    code: 'particle_size',
    label: 'Particle Size',
    dataType: 'text',
    validation: { maxLength: 100 },
  },
  {
    code: 'chopping_grade',
    label: 'Chopping Grade',
    dataType: 'select',
    allowedValues: [
      { value: 'normal', label: 'Normal Chopped' },
      { value: 'double', label: 'Double Chopped' },
    ],
  },
  {
    code: 'module_type',
    label: 'Module Type',
    dataType: 'select',
    allowedValues: [
      { value: 'folded', label: 'Folded Module' },
      { value: 'anchor', label: 'Anchor Module' },
    ],
  },
  {
    code: 'anchor_set',
    label: 'Anchor Set',
    dataType: 'reference',
    referenceModel: 'ItemMaster',
    referenceFamilyCode: 'ANCHOR_SET',
  },
  {
    code: 'brand_type',
    label: 'Brand Type',
    dataType: 'select',
    allowedValues: [
      { value: 'branded', label: 'Branded' },
      { value: 'plain', label: 'Plain' },
    ],
  },
  {
    code: 'print_color',
    label: 'Print Colour',
    dataType: 'text',
    validation: { maxLength: 80 },
  },
  {
    code: 'packing_capacity',
    label: 'Packing Capacity',
    dataType: 'number',
    validation: { min: 0.001, precision: 3 },
  },
]);

const requiredIdentity = code => ({
  attributeCode: code,
  required: true,
  identity: true,
});
const optionalIdentity = code => ({
  attributeCode: code,
  required: false,
  identity: true,
});

export const ITEM_FAMILY_CATALOG = Object.freeze([
  {
    code: 'ALUMINA',
    name: 'Alumina',
    classCode: 'PURCHASED_MATERIAL',
    skuPrefix: 'RM-ALU',
    attributes: [requiredIdentity('chemical_grade'), requiredIdentity('particle_size')],
    uomPolicy: { baseUom: 'kg' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'SILICA',
    name: 'Silica',
    classCode: 'PURCHASED_MATERIAL',
    skuPrefix: 'RM-SIL',
    attributes: [requiredIdentity('chemical_grade'), requiredIdentity('particle_size')],
    uomPolicy: { baseUom: 'kg' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'ZIRCONIA',
    name: 'Zirconia Sand / Silica',
    classCode: 'PURCHASED_MATERIAL',
    skuPrefix: 'RM-ZIR',
    attributes: [requiredIdentity('chemical_grade'), requiredIdentity('particle_size')],
    uomPolicy: { baseUom: 'kg' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'BLANKET',
    name: 'Ceramic Fibre Blanket',
    classCode: 'FINISHED_GOOD',
    skuPrefix: 'FG-BLK',
    attributes: [
      requiredIdentity('classification_temperature'),
      requiredIdentity('density'),
      requiredIdentity('length'),
      requiredIdentity('width'),
      requiredIdentity('thickness'),
      optionalIdentity('grade'),
    ],
    uomPolicy: { baseUom: 'roll', catchUom: 'kg', catchMode: 'MEASURED' },
    trackingPolicy: {
      lotTracked: true,
      serialTracked: true,
      serialControlMode: 'INFORMATIONAL',
    },
  },
  {
    code: 'BULK',
    name: 'Ceramic Fibre Bulk',
    classCode: 'FINISHED_GOOD',
    skuPrefix: 'FG-BULK',
    attributes: [
      requiredIdentity('classification_temperature'),
      requiredIdentity('grade'),
    ],
    uomPolicy: { baseUom: 'bag', catchUom: 'kg', catchMode: 'NOMINAL', nominalFactor: 20 },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'ET',
    name: 'ET',
    classCode: 'BY_PRODUCT',
    skuPrefix: 'BYP-ET',
    attributes: [requiredIdentity('classification_temperature')],
    uomPolicy: { baseUom: 'kg' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'CHOPPED_FIBRE',
    name: 'Chopped Ceramic Fibre',
    classCode: 'INTERMEDIATE',
    skuPrefix: 'WIP-CF',
    attributes: [
      requiredIdentity('classification_temperature'),
      requiredIdentity('chopping_grade'),
    ],
    uomPolicy: { baseUom: 'kg' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'SHORTS',
    name: 'Shorts',
    classCode: 'BY_PRODUCT',
    skuPrefix: 'BYP-SHORT',
    // Factory segregation rule: Shorts are separated by temperature only.
    attributes: [requiredIdentity('classification_temperature')],
    uomPolicy: { baseUom: 'kg' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'BOARD',
    name: 'Ceramic Fibre Board',
    classCode: 'FINISHED_GOOD',
    skuPrefix: 'FG-BRD',
    attributes: [
      requiredIdentity('classification_temperature'),
      requiredIdentity('length'),
      requiredIdentity('width'),
      requiredIdentity('thickness'),
      requiredIdentity('grade'),
    ],
    uomPolicy: { baseUom: 'nos' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'MODULE',
    name: 'Ceramic Fibre Module',
    classCode: 'FINISHED_GOOD',
    skuPrefix: 'FG-MOD',
    attributes: [
      requiredIdentity('classification_temperature'),
      requiredIdentity('density'),
      requiredIdentity('length'),
      requiredIdentity('width'),
      requiredIdentity('thickness'),
      requiredIdentity('module_type'),
      optionalIdentity('anchor_set'),
    ],
    uomPolicy: { baseUom: 'nos' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'MODULE_STRIP',
    name: 'Module Strip',
    classCode: 'INTERMEDIATE',
    skuPrefix: 'WIP-MSTRIP',
    attributes: [
      requiredIdentity('classification_temperature'),
      requiredIdentity('density'),
      requiredIdentity('length'),
      requiredIdentity('width'),
      requiredIdentity('thickness'),
    ],
    uomPolicy: { baseUom: 'nos', catchUom: 'kg', catchMode: 'MEASURED' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'PLASTIC_BAG',
    name: 'Plastic Bag',
    classCode: 'PACKAGING',
    skuPrefix: 'PACK-PB',
    attributes: [optionalIdentity('grade')],
    uomPolicy: { baseUom: 'nos' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'WOVEN_BAG',
    name: 'Woven Bag',
    classCode: 'PACKAGING',
    skuPrefix: 'PACK-WB',
    attributes: [
      requiredIdentity('length'),
      requiredIdentity('width'),
      requiredIdentity('brand_type'),
      optionalIdentity('print_color'),
    ],
    uomPolicy: { baseUom: 'nos' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'BOX',
    name: 'Box',
    classCode: 'PACKAGING',
    skuPrefix: 'PACK-BOX',
    attributes: [
      requiredIdentity('length'),
      requiredIdentity('width'),
      requiredIdentity('thickness'),
      requiredIdentity('brand_type'),
      optionalIdentity('print_color'),
      optionalIdentity('packing_capacity'),
    ],
    uomPolicy: { baseUom: 'nos' },
    trackingPolicy: { lotTracked: true },
  },
  {
    code: 'ANCHOR_SET',
    name: 'Anchor Set',
    classCode: 'COMPONENT',
    skuPrefix: 'COMP-ANCH',
    attributes: [requiredIdentity('grade'), optionalIdentity('width')],
    uomPolicy: { baseUom: 'nos' },
    trackingPolicy: { lotTracked: true },
  },
]);
